export const actionTypes = {
  INIT_FIREBASE: 'INIT_FIREBASE',
  CREATE_USER: 'CREATE_USER',
  SET_USER: 'SET_USER',
  
  SET_CRITERIAS: 'SET_CRITERIAS',
  SET_EVENTS: 'SET_EVENTS',
  SET_SETTINGS: 'SET_SETTINGS',
}
